stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
      - docker login -u chotam -p Danik0509
  script:
      - docker build -t chotam/serverfinalapp:python-dev .
  only:
    - main

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python manage.py test
  only:
    - main

deploy:
  stage: deploy
  image: docker:24.0.5
  script:
    - echo "Deploying project..."
    - docker push chotam/serverfinalapp:python-dev
  environment:
    name: production
    url: http://127.0.0.1:8000
  only:
    - main

